name: Delete environments/VMs

on:
  workflow_dispatch:
    inputs:
      hostname:
        type: string
        default: nightly
      domain:
        type: string

permissions:
  deployments: write

jobs:
  cleanup:
    runs-on: ubuntu-latest
    environment:
      name: ${{ inputs.hostname || vars.hostname }}
      url: https://${{ env.hostname }}.${{ env.domain }}
    steps:
      - uses: actions/checkout@HEAD
      - name: Clean up VM(s)
        run: |
          git clone https://eaas.dev/eaas-installer
          cd eaas-installer
          git clone "$dns_token_git_url"
          printf %s "$clouds_yaml" > clouds.yaml
          scripts/manage-test-servers-openstack.py -p "eaas-test-$hostname" -d "$domain" cleanup -k 0
          curl --oauth2-bearer "$GITHUB_TOKEN" -X DELETE "$GITHUB_API_URL/repos/$GITHUB_REPOSITORY/environments/$hostname"
    timeout-minutes: 10
    env:
      dns_token_git_url: ${{ secrets.dns_token_git_url }}
      clouds_yaml: ${{ secrets.clouds_yaml }}
      hostname: ${{ inputs.hostname || vars.hostname }}
      domain: ${{ inputs.domain || vars.domain }}
